# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: 'docker'
      PORT: 3000
      LOG_LEVEL: 'info'
      REQUEST_LIMIT: '100kb'
      PASETO_KEY: 'xu2QHnI7xKFEBHLtchqZCqLGsenq8ZvmbHqY58uLOm8='
      PASETO_ISSUER: 'api'
      PASETO_EXPIRE_AFTER_HOURS: '24'
      MAIL_HOST:
      MAIL_PORT:
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_FROM:
      WEBSITE_NAME: 'ExpressTS-api-starter'
      FRONTEND_URL: '"http://127.0.0.1:8080'
      VERIFICATION_URL: 'http://127.0.0.1:3000/auth/verify'
      PASSWORD_RESET_URL: 'http://127.0.0.1:8080/#/password/reset'
    command: /bin/sh -c "yarn configure database migrate --environment=docker && yarn start"
    ports:
      - "3000:3000"

  postgres:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

